version: "3.7"

services:
  ui:
    container_name: axle-ui
    depends_on:
      - server
    build:
      context: ./ui
      dockerfile: Dockerfile.prod
    ports:
      - 3000:80
  server:
    container_name: axle-server
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - "SearchEngineConfig:DatabaseConnectionURI=mongodb://axle-db:27017"
  db:
    image: mongo
    container_name: axle-db
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
