version: "3.7"

services:
  ui:
    container_name: axle-ui
    depends_on:
      - server
    build:
      context: ./ui
      dockerfile: Dockerfile
    volumes:
      - "./ui:/app"
      - "/app/node_modules"
    ports:
      - 3000:3000
  server:
    container_name: axle-server
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:80
    volumes:
      - ".:/app"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "SearchEngineConfig:DatabaseConnectionURI=mongodb://axle-db:27017"
  db:
    image: mongo
    container_name: axle-db
    ports:
      - 27017:27017
    restart: always
    volumes:
      - "./data/db:/data/db"
      - ".:/app"
