version: "3.7"

services:
  ui:
    container_name: axle-ui
    build:
      context: ./ui
      dockerfile: Dockerfile
    volumes:
      - "./ui:/app"
      - "/app/node_modules"
    ports:
      - 3000:3000
  server:
    container_name: axle-server
    build:
      dockerfile: Dockerfile
    ports:
      - 5000:5000
      - 5001:5001
    volumes:
      - ".:/app"
  mongodb:
    image: mongo
    container_name: axle-mongodb
    volumes:
      - /data/db:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
