FROM node:14.15.5 as build

WORKDIR /app

COPY package.json ./

RUN npm install

COPY . ./
RUN npm build

FROM nginx:stable-alpine
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]